# Generated by Django 4.1.6 on 2024-07-12 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transfert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('id_client_source', models.CharField(max_length=30)),
                ('id_abonne_source', models.CharField(max_length=30)),
                ('montant', models.IntegerField()),
                ('id_client_destination', models.CharField(max_length=30)),
                ('id_abonne_destination', models.CharField(max_length=30)),
            ],
        ),
    ]
