# Generated by Django 4.1.6 on 2024-07-12 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transferts', '0002_alter_transfert_id_abonne_destination_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfert',
            name='id_abonne_source',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
